package vn.gpay.gsmart.core.utils;

public class ColumnPersonnel {
	public static int MaSoMoi			= 0;
	public static int TinhTrang  		= 1;
	public static int ThoiVu			= 2;
	public static int Ho 				= 3;
	public static int Ten		  		= 4;
	public static int HoVaTen  			= 5;
	public static int GT	  			= 6;
	public static int NgaySinh	  		= 7;
	public static int BoPhan	  		= 8;
	public static int ChucVu		  	= 9;
	public static int ChucVutrongBH		= 10;
	public static int Bac				= 11;
	public static int MaBacluongBH  	= 12;
	public static int HeSoLuongBH		= 13;
	public static int MucLuongDongBH	= 14;
	public static int MucLuongHT  		= 15;
	public static int HeSoCV		  	= 16;
	public static int ThangGiamBH	  	= 17;
	public static int NgayVaoCT  		= 18;
	public static int NgayThoiViec  	= 19;
	public static int LyDo	  			= 20;
	public static int NgayKiHDTV	  	= 21;
	public static int NgayKiHDCTH  		= 22;
	public static int NgayKiHDVTH		= 23;
	public static int NgayDongBH		= 24;
	public static int SoTaiKhoan		= 25;
	public static int Thon				= 26;
	public static int Xa				= 27;
	public static int Huyen				= 28;
	public static int Tinh				= 29;
	public static int DiaChi			= 30;
	public static int DienThoai			= 31;
	public static int CMND				= 32;
	public static int NgayCap			= 33;
	public static int NoiCap			= 34;
	public static int CMTM 				= 35; 
	public static int NgayCapMoi		= 36;
	public static int NoiCapMoi			= 37;
	public static int SucKhoe			= 38;
	public static int SoSBH				= 39;
	public static int SoSoHoKhau		= 40;
}
